"""Russian copy for the project docs. Keys are exact fragments of the generated HTML."""

PHRASES = {
    "Coding agents can produce a settings page in seconds. They are much worse at using the design system you already have: they invent a Button, hardcode <code>#8B5CF6</code>, skip tokens, and ignore composition rules.": "Агент собирает страницу настроек за секунды. Гораздо хуже он пользуется уже существующей системой: рисует свой Button, хардкодит <code>#8B5CF6</code>, пропускает токены и игнорирует правила композиции.",
    "ds-eval turns that into a measurable question. Same tasks, same design system, different models or prompts — then a score you can compare and regress on.": "ds-eval превращает это в измеримый вопрос. Одни и те же задачи, одна система, разные модели или промпты — и счёт, который можно сравнить и прогнать на регрессию.",
    "<strong>Compare models</strong>": "<strong>Сравнить модели</strong>",
    "Claude, Codex, Gemini, Grok, or a local model — one suite, one report": "Claude, Codex, Gemini, Grok или локальная модель — один набор, один отчёт",
    "<strong>Catch prompt regressions</strong>": "<strong>Ловить регрессии промпта</strong>",
    "Prompt v12 vs v13: what improved, what broke, which cases flipped": "Промпт v12 против v13: что выросло, что сломалось, какие кейсы перевернулись",
    "<strong>Use your own DS</strong>": "<strong>Своя система</strong>",
    "Tokens, React components, Storybook, docs, and UX patterns as the source of truth": "Токены, React-компоненты, Storybook, документация и UX-паттерны как источник правды",
    "Each eval case starts from an isolated starter app. The model receives the design system, the task prompt, and must generate working UI. The harness then builds, screenshots, and grades the result.": "Каждый кейс стартует из изолированного приложения. Модель получает дизайн-систему и задачу и должна собрать рабочий интерфейс. Дальше harness собирает проект, снимает скриншот и ставит оценку.",
    "Python eval engine. Fixture models run offline. Live models read keys from env — never from config.": "Движок на Python. Фикстуры работают офлайн. Живые модели читают ключи из окружения, не из конфига.",
    "With API keys:": "С ключами API:",
    "<code>report</code> writes <code>report.json</code>, <code>report.html</code>, and <code>summary.md</code> from the run artifacts. The table below is the offline fixture smoke run, not Claude or Codex.": "<code>report</code> пишет <code>report.json</code>, <code>report.html</code> и <code>summary.md</code> из артефактов прогона. Таблица ниже — офлайн smoke на фикстурах, не Claude и не Codex.",
    "100 cases, written as real product tasks — not 100 copies of “make a button”. Easy / medium / hard, plus cases that deliberately conflict with DS rules.": "100 кейсов, написанных как продуктовые задачи, а не сто копий «сделай кнопку». Лёгкие, средние и сложные, плюс кейсы, которые специально спорят с правилами системы.",
    "Cases are YAML with a Pydantic schema: required components, forbidden patterns, assertions, rubric, viewport.": "Кейсы — это YAML со схемой Pydantic: обязательные компоненты, запрещённые паттерны, проверки, рубрика, вьюпорт.",
    "The overall score is not a single LLM opinion. Deterministic graders and LLM judges are tracked separately on the dashboard.": "Общий счёт — не одно мнение модели. Проверки по правилам и судьи на LLM на дашборде лежат отдельно.",
    "Static / AST": "Статика / AST",
    "DS imports vs raw <code>&lt;button&gt;</code>, hardcoded colors, spacing tokens, duplicate components": "Импорты из системы против сырого <code>&lt;button&gt;</code>, захардкоженные цвета, токены отступов, дубли компонентов",
    "Component compliance": "Соответствие компонентам",
    "Required / forbidden components, variants, props, composition rules": "Обязательные и запрещённые компоненты, варианты, пропсы, правила композиции",
    'Runtime <span class="tag tag-det">правило</span>': 'Рантайм <span class="tag tag-det">правило</span>',
    "Build, Playwright, console errors, dialogs, tabs, form submit": "Сборка, Playwright, ошибки консоли, диалоги, табы, отправка формы",
    'Accessibility <span class="tag tag-det">правило</span>': 'Доступность <span class="tag tag-det">правило</span>',
    "axe-core plus labels, keyboard, focus, semantics, ARIA": "axe-core плюс подписи, клавиатура, фокус, семантика, ARIA",
    'Visual <span class="tag tag-llm">LLM</span>': 'Визуал <span class="tag tag-llm">LLM</span>',
    "Layout, hierarchy, spacing, alignment, consistency, polish — each 0–5 with reasoning": "Раскладка, иерархия, отступы, выравнивание, цельность, аккуратность — каждый критерий от 0 до 5 с объяснением",
    'Product UX <span class="tag tag-llm">LLM</span>': 'Продуктовый UX <span class="tag tag-llm">LLM</span>',
    "Task completion, pattern correctness, error prevention, feedback, IA": "Задача сделана, паттерн верный, ошибки предотвращаются, есть обратная связь, ясна структура",
    'Code quality <span class="tag tag-llm">LLM</span>': 'Качество кода <span class="tag tag-llm">LLM</span>',
    "Structure, duplication, types, React practices, unnecessary abstraction": "Структура, дубли, типы, практики React, лишняя абстракция",
    "Weights are configurable. Default mix for the overall score:": "Веса настраиваются. Смесь по умолчанию для общего счёта:",
    "Every generation and judge call stores input/output tokens, estimated cost, and latency. The dashboard shows benchmark cost and cost per eval.": "Каждый вызов генерации и судьи сохраняет входные и выходные токены, оценку стоимости и задержку. Дашборд показывает стоимость бенчмарка и цену одного кейса.",
    "Compare two runs — model versions or prompt versions — and see what moved.": "Сравнивает два прогона — версии модели или версии промпта — и показывает, что сдвинулось.",
    "Each flipped case keeps before/after screenshots, grader explanations, and the generated source.": "У каждого перевернувшегося кейса остаются скриншоты до и после, объяснения проверок и сгенерированный код.",
    "A local research UI over SQLite run history. Overview, models, runs, cases, and a comparison view for any two outputs of the same task.": "Локальный интерфейс исследователя поверх истории прогонов в SQLite. Обзор, модели, прогоны, кейсы и сравнение двух ответов на одну задачу.",
    "<strong>Overview</strong>": "<strong>Обзор</strong>",
    "Overall score, categories, pass rate, cost, tokens, latency": "Общий счёт, категории, доля прошедших, стоимость, токены, задержка",
    "<strong>Cases</strong>": "<strong>Кейсы</strong>",
    "Filter by model, category, difficulty, pass/fail, grader": "Фильтр по модели, категории, сложности, прошёл или нет, проверке",
    "<strong>Case detail</strong>": "<strong>Карточка кейса</strong>",
    "Prompt, rendered UI, screenshot, source, rubric, logs, cost": "Промпт, собранный интерфейс, скриншот, исходник, рубрика, логи, стоимость",
    "Ships with a demo DS (Button, Input, Select, Dialog, Table, tokens, a few UX patterns) so the repo runs from clone. Point it at yours with a manifest:": "В репозитории есть демо-система (Button, Input, Select, Dialog, Table, токены и несколько UX-паттернов), чтобы проект запускался сразу после клона. Своя система подключается манифестом:",
    "LLM judges are not ground truth. Visual and UX scores are subjective, even with a rubric and optional multi-judge setup. Deterministic graders (imports, tokens, axe, Playwright) are the reliable core; treat the rest as signal, not a verdict.": "Судьи на LLM — не истина. Визуал и UX субъективны, даже с рубрикой и несколькими судьями. Надёжное ядро — проверки по правилам: импорты, токены, axe, Playwright. Остальное — сигнал, не приговор.",
    "A high score means the model followed this design system on this suite. It does not mean the generated UI is production-ready for your product.": "Высокий балл значит, что модель следовала этой системе на этом наборе. Он не значит, что экран готов в продакшен вашего продукта.",
    "ds-eval sits after the agent writes UI, before you trust the output in production:": "ds-eval стоит после того, как агент написал интерфейс, и до того, как вы доверяете этому коду в продакшене:",
    "<strong>Colors</strong>": "<strong>Цвета</strong>",
    "How many text and background colors exist. Rewards fewer unique values and CSS variable usage.": "Сколько цветов текста и фона на странице. Чем меньше уникальных значений и чем больше CSS-переменных, тем выше счёт.",
    "<strong>Typography</strong>": "<strong>Типографика</strong>",
    "Font families, sizes, and weights in visible text. Fewer means more controlled.": "Семейства, размеры и начертания видимого текста. Чем их меньше, тем собраннее система.",
    "<strong>Spacing</strong>": "<strong>Отступы</strong>",
    "How many distinct padding and gap values appear. Converging to a scale is ideal.": "Сколько разных значений padding и gap. Хорошо, когда они сходятся к шкале.",
    "<strong>Radius</strong>": "<strong>Радиус</strong>",
    "Distinct non-zero border-radius values. Fewer = more consistent corners.": "Сколько ненулевых радиусов. Меньше — ровнее углы.",
    "Open <code>http://localhost:3000</code>. If the port is busy:": "Открой <code>http://localhost:3000</code>. Если порт занят:",
    "If Playwright can't find a browser:": "Если Playwright не находит браузер:",
    "The tool loads the page in a real Chromium browser (via Playwright), samples visible elements, reads their computed styles, and generates a health report with scores, signals, and recommendations.": "Инструмент открывает страницу в настоящем Chromium через Playwright, снимает видимые элементы, читает computed styles и собирает отчёт: счёт, сигналы и рекомендации.",
    "Returns <code>{ \"ok\": true }</code> — use for uptime checks.": "Возвращает <code>{ \"ok\": true }</code> — удобно для проверки, что сервис жив.",
    "Result from analyzing <code>barvian.me</code> — a disciplined, minimalist site:": "Результат разбора <code>barvian.me</code> — собранный минималистичный сайт:",
    "A page with many competing values — typical of legacy UIs or rapid prototyping:": "Страница с кучей конкурирующих значений — обычная история легаси и быстрых прототипов:",
    "The most useful pattern: <strong>score first</strong>, then summary, then priorities, then supporting values.": "Удобный порядок чтения: <strong>сначала счёт</strong>, потом резюме, потом приоритеты, потом сырые значения.",
    "Use ds-health as the verification step in your design system workflow:": "ds-health — шаг проверки в цепочке дизайн-системы:",
    "Open <a href=\"https://www.figma.com/settings\" target=\"_blank\" rel=\"noopener noreferrer\">Figma Settings</a> → Personal access tokens → Create with <strong>File content: Read-only</strong> scope.": "Открой <a href=\"https://www.figma.com/settings\" target=\"_blank\" rel=\"noopener noreferrer\">настройки Figma</a> → Personal access tokens → создай токен с правом <strong>File content: Read-only</strong>.",
    "From any Figma URL:": "Из любого URL Figma:",
    "Top-level overview with counts and links to all detailed files.": "Верхний обзор: счётчики и ссылки на подробные файлы.",
    "Variables with multiple modes (e.g., Light / Dark) show all values.": "У переменных с несколькими режимами (например, Light / Dark) выводятся все значения.",
    "What a generated <code>colors.md</code> looks like:": "Как выглядит сгенерированный <code>colors.md</code>:",
    "What a generated component file looks like:": "Как выглядит файл компонента:",
    "The tool automatically detects potential issues and writes them to <code>gaps.md</code>:": "Инструмент сам замечает возможные проблемы и пишет их в <code>gaps.md</code>:",
    "<strong>Missing descriptions</strong>": "<strong>Нет описаний</strong>",
    "Components without Figma descriptions — agents can't understand intent": "У компонентов нет описания в Figma — агент не понимает замысел",
    "<strong>No tokens found</strong>": "<strong>Нет токенов</strong>",
    "File has no local variables — specs will be incomplete": "В файле нет локальных переменных — спека будет неполной",
    "<strong>Undocumented components</strong>": "<strong>Компоненты без документации</strong>",
    "Components exist but lack descriptions for agent consumption": "Компоненты есть, но описания, которое сможет прочитать агент, нет",
    "Combine with <a href=\"design-system-ai-starter.html\">design-system-ai-starter</a> for a full workflow:": "Вместе с <a href=\"design-system-ai-starter.html\">design-system-ai-starter</a> получается полный путь:",
    "According to analysis of 5,000+ enterprise repositories, 74% of React components contain at least three hardcoded color or spacing values that bypass the design system. ds-lint finds them.": "По разбору 5 000+ корпоративных репозиториев, в 74% React-компонентов есть минимум три захардкоженных цвета или отступа в обход системы. ds-lint их находит.",
    "<code>#hex</code>, <code>rgb()</code>, <code>rgba()</code>, <code>hsl()</code>, <code>hsla()</code>, named CSS colors (red, blue, etc.)": "<code>#hex</code>, <code>rgb()</code>, <code>rgba()</code>, <code>hsl()</code>, <code>hsla()</code> и именованные цвета CSS (red, blue и другие)",
    "<code>padding</code>, <code>margin</code>, <code>gap</code>, <code>top/right/bottom/left</code>, <code>width/height</code> in px/rem": "<code>padding</code>, <code>margin</code>, <code>gap</code>, <code>top/right/bottom/left</code>, <code>width/height</code> в px/rem",
    "<strong>Font Sizes</strong>": "<strong>Размеры шрифта</strong>",
    "<code>font-size</code>, <code>line-height</code>, <code>letter-spacing</code> in px/rem": "<code>font-size</code>, <code>line-height</code>, <code>letter-spacing</code> в px/rem",
    "<code>border-radius</code> in px/rem (skips 0px)": "<code>border-radius</code> в px/rem (ноль пропускает)",
    "Scans: <code>.js</code> <code>.jsx</code> <code>.ts</code> <code>.tsx</code> <code>.css</code> <code>.scss</code> <code>.vue</code> <code>.svelte</code>": "Смотрит: <code>.js</code> <code>.jsx</code> <code>.ts</code> <code>.tsx</code> <code>.css</code> <code>.scss</code> <code>.vue</code> <code>.svelte</code>",
    "Skips: <code>node_modules</code>, <code>dist</code>, <code>build</code>, <code>.next</code>, <code>.git</code>, CSS variable declarations": "Пропускает: <code>node_modules</code>, <code>dist</code>, <code>build</code>, <code>.next</code>, <code>.git</code> и объявления CSS-переменных",
    "Provide a token file with <code>--tokens</code> to get replacement suggestions:": "Передай файл токенов через <code>--tokens</code>, чтобы получить подсказки замены:",
    "Works with output from <a href=\"figma-to-design-md.html\">figma-to-design-md</a> — token tables are parsed automatically.": "Понимает вывод <a href=\"figma-to-design-md.html\">figma-to-design-md</a> — таблицы токенов разбираются сами.",
    "Add a comment on the line above to skip specific values:": "Комментарий строкой выше пропускает конкретные значения:",
    "<code>--strict</code> exits with code 1 when violations are found, failing the CI step.": "<code>--strict</code> завершается с кодом 1, если нарушения есть, и роняет шаг CI.",
    "ds-lint fits between token definition and adoption tracking:": "ds-lint стоит между описанием токенов и учётом внедрения:",
    "AI agents are good at implementation, but weak at consistency. They commonly:": "Агенты хорошо пишут реализацию и плохо держат цельность. Обычно они:",
    "<strong>Invent values</strong>": "<strong>Выдумывают значения</strong>",
    "Pick 12px instead of your spacing token, or a plausible blue instead of your semantic link color": "Ставят 12px вместо шага вашей шкалы или правдоподобный синий вместо семантического цвета ссылки",
    "<strong>Miss composition rules</strong>": "<strong>Пропускают композицию</strong>",
    "Understand a component API but not when and how to combine components": "Знают API компонента, но не знают, когда и как компоненты собирать вместе",
    "<strong>Lose context</strong>": "<strong>Теряют контекст</strong>",
    "Drift between sessions — each conversation starts from scratch": "Плывут между сессиями: каждый разговор начинается с нуля",
    "<strong>This tool fixes it</strong>": "<strong>Что делает инструмент</strong>",
    "Creates a stable, local, project-readable source of truth for agents": "Кладёт в репозиторий устойчивый источник правды, который агент читает локально",
    "Run directly with npx or install globally.": "Запускается через npx или ставится глобально.",
    "Three commands to go from zero to AI-readable specs:": "Три команды от пустого проекта до спеки, которую читает агент:",
    "<strong>Design systems teams</strong>": "<strong>Команды дизайн-систем</strong>",
    "With existing tokens or theme files that agents should respect": "Уже есть токены или тема, которые агент должен соблюдать",
    "<strong>Frontend teams using AI</strong>": "<strong>Фронтенд-команды с AI</strong>",
    "Cursor, Claude Code, Copilot — any agent that writes UI code": "Cursor, Claude Code, Copilot — любой агент, который пишет интерфейс",
    "<strong>Product teams</strong>": "<strong>Продуктовые команды</strong>",
    "That want AI to stop inventing colors, spacing, and component behavior": "Хотят, чтобы AI перестал выдумывать цвета, отступы и поведение компонентов",
    "Scaffolds the AI-readable structure into an existing project.": "Раскладывает в существующем проекте структуру, которую читает агент.",
    "Reads your real token source and updates markdown specs.": "Читает настоящий источник токенов и обновляет markdown-спеки.",
    "Checks if all AI-readable files exist and are complete.": "Проверяет, что все файлы для агента на месте и заполнены.",
    "You already have tokens. This tool creates the agent-readable layer on top.": "Токены уже есть. Инструмент добавляет слой, который агент умеет читать.",
    "Input file with CSS custom properties:": "Входной файл с CSS-переменными:",
    "Run sync-tokens → get structured markdown with tables, categories, and agent-readable format.": "Команда sync-tokens собирает markdown с таблицами, категориями и форматом для агента.",
    "DTCG-format token file:": "Файл токенов в формате DTCG:",
    "What each generated file contains:": "Что лежит в каждом сгенерированном файле:",
    "Pairs with <code>figma-to-design-md</code> for a full Figma-to-AI pipeline:": "Вместе с <code>figma-to-design-md</code> это путь от Figma до агента:",
    "ds-eval scores the UI after the model has a context pack and, if needed, a repair pass:": "ds-eval ставит счёт после того, как у модели есть пакет контекста и, если нужно, проход починки:",
    "ds-lint is the gate in code, before a model is allowed to see the system:": "ds-lint — ворота в коде, до того как модель увидит систему:",
    "The markdown from Figma is the input ds-context packs for a model:": "Markdown из Figma — это вход, который ds-context упаковывает для модели:",
    "ds-health checks the live page after the model loop, when the UI is already in production:": "ds-health проверяет живую страницу после контура модели, когда интерфейс уже на проде:",
    "ds-coverage counts whether the codebase imports the system the model was told to use:": "ds-coverage считает, импортирует ли код ту систему, которую показали модели:",
    "A design system leaks when a component next to the tokens still writes a raw color or spacing value. ds-lint finds those values and, when a token file is nearby, suggests the system name.": "Система протекает, когда рядом с токенами компонент всё ещё пишет сырой цвет или отступ. ds-lint находит такие значения и, если рядом есть файл токенов, предлагает имя из системы.",
    "Adoption is the #1 challenge in design systems. Teams build component libraries but can't prove they're being used. Satisfaction can drop from 68% to 31% within a year while \"adoption\" metrics look healthy.": "Внедрение — главная боль дизайн-систем. Библиотеку собирают, а доказать, что ей пользуются, не могут. Удовлетворённость за год может упасть с 68% до 31%, пока метрики «внедрения» выглядят здоровыми.",
    "ds-coverage gives you real numbers: which components are imported, how often, and what's being reimplemented locally instead.": "ds-coverage даёт числа: какие компоненты импортируют, как часто и что рядом написано заново.",
    "<strong>Components Used</strong>": "<strong>Используемые компоненты</strong>",
    "How many DS components appear in import statements across the codebase": "Сколько компонентов системы встречается в импортах по кодовой базе",
    "<strong>Total Imports</strong>": "<strong>Всего импортов</strong>",
    "Total number of DS import occurrences — measures adoption depth": "Сколько раз систему импортировали — глубина внедрения",
    "<strong>Custom Components</strong>": "<strong>Местные компоненты</strong>",
    "Local components imported from relative paths — potential DS candidates": "Компоненты из относительных путей — кандидаты в систему",
    "<strong>Duplicates</strong>": "<strong>Дубли</strong>",
    "Local components with the same name as DS components — likely reimplementations": "Местные компоненты с тем же именем, что у системных — скорее всего написаны заново",
    "<strong>Unused Components</strong>": "<strong>Неиспользуемые</strong>",
    "DS components never imported anywhere — deprecation candidates (requires --inventory)": "Компоненты системы, которые нигде не импортированы — кандидаты на удаление (нужен --inventory)",
    "A team that actively uses their design system:": "Команда, которая системой реально пользуется:",
    "A codebase where teams bypass the design system:": "Кодовая база, где систему обходят:",
    "To detect unused components, provide a JSON file listing all exports from your DS package:": "Чтобы найти неиспользуемые компоненты, передай JSON со всеми экспортами пакета системы:",
    "You can also point to the index file of your DS package — ds-coverage will parse its exports.": "Можно указать index-файл пакета: ds-coverage сам разберёт экспорты.",
    "<code>--min</code> exits with code 1 when coverage is below the threshold.": "<code>--min</code> завершается с кодом 1, если покрытие ниже порога.",
    "ds-coverage is the adoption layer in the design system workflow:": "ds-coverage — слой внедрения в цепочке дизайн-системы:",
    "<th>Fixture</th>": "<th>Фикстура</th>",
    "<th>Naive</th>": "<th>Наивный</th>",
    "<td>Functional</td>": "<td>Функции</td>",
    "<td>Build</td>": "<td>Сборка</td>",
    "<td>Code</td>": "<td>Код</td>",
    "<span>Fixture</span>": "<span>Фикстура</span>",
    "<span>Naive</span>": "<span>Наивный</span>",
    "<td>Component</td>": "<td>Компоненты</td>",
    "<td>Correct use of Button, Select, Tabs, Dialog, Toast…</td>": "<td>Верное использование Button, Select, Tabs, Dialog, Toast…</td>",
    "<td>Patterns</td>": "<td>Паттерны</td>",
    "<td>Destructive confirm, empty states, bulk actions, multi-step</td>": "<td>Подтверждение удаления, пустые состояния, массовые действия, несколько шагов</td>",
    "<td>Pages</td>": "<td>Страницы</td>",
    "<td>Settings, billing, permissions, employee profile</td>": "<td>Настройки, оплата, права, профиль сотрудника</td>",
    "<td>Accessibility</td>": "<td>Доступность</td>",
    "<td>Keyboard, labels, ARIA, contrast, focus</td>": "<td>Клавиатура, подписи, ARIA, контраст, фокус</td>",
    "<td>Edge cases</td>": "<td>Крайние случаи</td>",
    "<td>Long strings, empty data, 100+ rows, mobile, i18n</td>": "<td>Длинные строки, пустые данные, 100+ строк, мобильный, i18n</td>",
    "<td>Adversarial</td>": "<td>Намеренные ловушки</td>",
    "<td>Prompt pushes a raw color or extra actions the DS forbids</td>": "<td>Промпт подталкивает к сырому цвету или лишним действиям, которые система запрещает</td>",
    "<td>DS Compliance</td>": "<td>Следование системе</td>",
    "<td>AST + component grader</td>": "<td>AST и проверка компонентов</td>",
    "<td>Playwright interactions</td>": "<td>Взаимодействия в Playwright</td>",
    "<td>Visual</td>": "<td>Визуал</td>",
    "<td>Vision LLM, rubric 0–5</td>": "<td>Vision-модель, рубрика 0–5</td>",
    "<td>Product UX</td>": "<td>Продуктовый UX</td>",
    "<td>UX judge</td>": "<td>UX-судья</td>",
    "<td>axe + assertions</td>": "<td>axe и проверки</td>",
    "<td>Code Quality</td>": "<td>Качество кода</td>",
    "<td>Static + LLM</td>": "<td>Статика и LLM</td>",
    "<td>Build Reliability</td>": "<td>Надёжность сборки</td>",
    "<td>Install / build / boot</td>": "<td>Установка, сборка, запуск</td>",
    "<td>string</td>": "<td>строка</td>",
    "<td>Public HTTP/HTTPS URL to analyze</td>": "<td>Публичный HTTP/HTTPS-адрес страницы</td>",
    "<td>number</td>": "<td>число</td>",
    "<td>0–100 average score</td>": "<td>Средний балл от 0 до 100</td>",
    "<td>Color consistency score</td>": "<td>Оценка цельности цвета</td>",
    "<td>Typography consistency score</td>": "<td>Оценка цельности типографики</td>",
    "<td>Spacing consistency score</td>": "<td>Оценка цельности отступов</td>",
    "<td>Radius consistency score</td>": "<td>Оценка цельности скруглений</td>",
    '<td>"Healthy", "Mostly consistent", etc.</td>': "<td>«Здоровый», «В целом цельный» и другие</td>",
    "<td>Plain-English interpretation</td>": "<td>Короткий вывод обычным языком</td>",
    "<td>array</td>": "<td>массив</td>",
    "<td>What to fix first</td>": "<td>Что чинить первым</td>",
    "<td>Actionable next steps</td>": "<td>Конкретные следующие шаги</td>",
    "<td>Individual observations</td>": "<td>Отдельные наблюдения</td>",
    "<td>object</td>": "<td>объект</td>",
    "<td>Most common values per category</td>": "<td>Самые частые значения по категориям</td>",
    "<td>Color</td>": "<td>Цвет</td>",
    "<td>Typography</td>": "<td>Типографика</td>",
    "<td>Spacing</td>": "<td>Отступы</td>",
    "<td>Radius</td>": "<td>Скругление</td>",
    "<td>Overall health</td>": "<td>Общее здоровье</td>",
    "<td>Average of 4 category scores — quick pass/fail signal</td>": "<td>Среднее четырёх оценок — быстрый сигнал «прошло / не прошло»</td>",
    "<td>Executive summary</td>": "<td>Короткий вывод</td>",
    "<td>Plain-English conclusion for stakeholders</td>": "<td>Вывод для тех, кто не читает сырые цифры</td>",
    "<td>Priority issues</td>": "<td>Приоритеты</td>",
    "<td>What's worth fixing first — biggest impact items</td>": "<td>Что чинить первым — с наибольшим эффектом</td>",
    "<td>Recommendations</td>": "<td>Рекомендации</td>",
    "<td>Practical cleanup steps you can assign to a sprint</td>": "<td>Практичные шаги, которые можно поставить в спринт</td>",
    "<td>Signals</td>": "<td>Сигналы</td>",
    "<td>Individual observations — raw evidence behind the score</td>": "<td>Отдельные наблюдения — сырые доказательства за оценкой</td>",
    "<td>Top values</td>": "<td>Частые значения</td>",
    "<td>Most common colors/sizes/spacing — where consolidation helps most</td>": "<td>Самые частые цвета, размеры и отступы — где сведение в токены даст больше всего</td>",
    "<td>Normalized groups</td>": "<td>Сведённые группы</td>",
    "<td>Near-identical values collapsed into cleaner buckets</td>": "<td>Почти одинаковые значения собраны в более чистые группы</td>",
    "<td>Healthy</td>": "<td>Здоровый</td>",
    "<td>Tightly controlled — few colors, restrained typography, small spacing set</td>": "<td>Жёстко собрано: мало цветов, сдержанная типографика, небольшой набор отступов</td>",
    "<td>Mostly consistent</td>": "<td>В целом цельный</td>",
    "<td>Some fragmentation or a few one-off values</td>": "<td>Есть разрозненность или несколько разовых значений</td>",
    "<td>Needs attention</td>": "<td>Нужно внимание</td>",
    "<td>Visual system may be drifting — needs a closer look</td>": "<td>Визуальная система расползается — стоит посмотреть ближе</td>",
    "<td>Fragmented</td>": "<td>Раздробленный</td>",
    "<td>Too many competing values — likely no token layer</td>": "<td>Слишком много конкурирующих значений — слоя токенов, скорее всего, нет</td>",
    "<td>Figma file key (required)</td>": "<td>Ключ файла Figma (обязательно)</td>",
    "<td>Figma personal access token</td>": "<td>Персональный токен Figma</td>",
    "<td>Output directory</td>": "<td>Папка для результата</td>",
    "<td>Scope to a specific page/frame</td>": "<td>Ограничить страницей или фреймом</td>",
    "<td>Print version</td>": "<td>Показать версию</td>",
    "<td>Print help</td>": "<td>Показать справку</td>",
    "<td>All COLOR variables + FILL styles in markdown tables</td>": "<td>Все переменные COLOR и стили FILL в markdown-таблицах</td>",
    "<td>Font-related variables + TEXT styles</td>": "<td>Переменные шрифта и стили TEXT</td>",
    "<td>Variables matching space, gap, padding, margin</td>": "<td>Переменные с space, gap, padding, margin</td>",
    "<td>Variables matching radius, round, corner</td>": "<td>Переменные с radius, round, corner</td>",
    "<td>Directory or file to scan</td>": "<td>Папка или файл для проверки</td>",
    "<td>Token source (.css, .json, or .md)</td>": "<td>Источник токенов (.css, .json или .md)</td>",
    "<td>Write report to file</td>": "<td>Записать отчёт в файл</td>",
    "<td>Exit with code 1 if violations found</td>": "<td>Код 1, если нашлись нарушения</td>",
    "<td>Cursor agent rule</td>": "<td>Правило агента Cursor</td>",
    "<td>Claude Code guide</td>": "<td>Инструкция для Claude Code</td>",
    "<td>Generic agent guide</td>": "<td>Общая инструкция для агента</td>",
    "<td>Color, spacing, typography, radius, motion</td>": "<td>Цвет, отступы, типографика, скругление, движение</td>",
    "<td>Full token list</td>": "<td>Полный список токенов</td>",
    "<td>Component spec template</td>": "<td>Шаблон спеки компонента</td>",
    "<td>Path to CSS or JSON token file</td>": "<td>Путь к CSS или JSON с токенами</td>",
    "<td>Project directory with specs/</td>": "<td>Папка проекта со specs/</td>",
    "<td>CSS variables</td>": "<td>CSS-переменные</td>",
    "<td>tokens.css with --color-primary: #3b82f6</td>": "<td>tokens.css с --color-primary: #3b82f6</td>",
    "<td>Custom JSON</td>": "<td>Свой JSON</td>",
    "<td>Name/value arrays</td>": "<td>Массивы имя/значение</td>",
    "<td>Markdown table of all color tokens with names and values</td>": "<td>Markdown-таблица цветовых токенов с именами и значениями</td>",
    "<td>Spacing scale with token names and pixel values</td>": "<td>Шкала отступов: имя токена и пиксели</td>",
    "<td>Font sizes, weights, line-heights</td>": "<td>Кегли, насыщенность, интерлиньяж</td>",
    "<td>Border-radius tokens</td>": "<td>Токены скругления</td>",
    "<td>Duration and easing tokens</td>": "<td>Токены длительности и сглаживания</td>",
    "<td>Complete flat list of all tokens</td>": "<td>Плоский список всех токенов</td>",
    "<td>Cursor agent rule referencing specs</td>": "<td>Правило Cursor со ссылками на спеки</td>",
    "<td>Claude-specific instructions with token paths</td>": "<td>Инструкция для Claude с путями к токенам</td>",
    "<td>Directory to scan</td>": "<td>Папка для проверки</td>",
    "<td>Comma-separated DS package names (required)</td>": "<td>Имена пакетов системы через запятую (обязательно)</td>",
    "<td>JSON file listing all DS components</td>": "<td>JSON со всеми компонентами системы</td>",
    "<td>Fail if coverage below threshold</td>": "<td>Ошибка, если покрытие ниже порога</td>",
    "<td>DS Components</td>": "<td>Компоненты системы</td>",
    "<td>Coverage</td>": "<td>Покрытие</td>",
    "<td>Duplicates</td>": "<td>Дубли</td>",
}
